User.shape: person

User -> buenzlimarks.web app
User -> buenzlimarks.browser extension

buenzlimarks: {
  web app: {
    label: "web app [React SPA]"
    description: {
      shape: text
      label: "displays and manages stored bookmarks, fully features GUI app"
    }
  }
  browser extension.description: {
    shape: text
    label: "provides often used features anywhere in the browser, e.g. adding a new bookmark"
  }

  web app -> backend: |md
    fetches and stores data
    [REST API]

    receives live updates
    [websocket]
  |
  browser extension -> backend: |md
    fetches and stores data
    [REST API]
  |

  backend: {
    description: {
      shape: text
      label: "[Rust Axum API server]"
    }
  }
}
