User.shape: person

User -> buenzlimarks

buenzlimarks: "buenzlimarks\n[Software System]"

buenzlimarks -> OAuth Provider: provides authentication with

User -> OAuth Provider: authenticates themselves with

OAuth Provider: {
  github: {
    shape: image
    icon: ./docs/src/assets/logo_github.svg
    label: ""
  }
  google: {
    shape: image
    icon: ./docs/src/assets/logo_google.svg
    label: ""
  }
}

buenzlimarks -> browser.IdexedDB: caches user data locally with

browser.logo: {
  shape: image
  icon: ./docs/src/assets/logo_firefox.svg
  label: ""
}

browser.IdexedDB.shape: cylinder
